Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -32,6 +32,13 @@ jobs:
       - name: Build with Maven
         run: mvn clean package -DskipTests
 
+      - name: Check if jar file exists
+        run: |
+          if [ ! -f target/peanut-0.0.1-SNAPSHOT.jar ]; then
+            echo "Error: Jar file not found!"
+            exit 1
+          fi
+
       - name: Docker build and push
         run: |
           docker login -u ${{ secrets.PEANUT_DOCKER_REPO }} -p ${{ secrets.PEANUT_DOCKER_KEY }}
